name: Generate APT Repo

on:
  push:
    branches:
      - main
    paths:
      - 'debs/**'  # 仅当 debs 文件夹内有文件变动时触发

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install APT Utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev bzip2 xz-utils

    - name: Scan Packages and Compress
      run: |
        # 扫描 debs 目录，生成 Sileo 所需的 Packages 索引
        dpkg-scanpackages -m debs /dev/null > Packages
        
        # 压缩为多种格式以兼容不同的包管理器
        bzip2 -fk Packages
        xz -fk Packages

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Packages Packages.bz2 Packages.xz
        git commit -m "Automated update: Packages index" || exit 0
        git push origin main
